apiVersion: v1
kind: Service
metadata:
  name: nginx-lb 
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
    component: frontend 
    version: "1.0.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      NodePort: 30000

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-lb
  labels:
    project: expense
    environment: dev
    component: frontend 
    version: "1.0.0"
spec:
  containers:
  - name: nginx
    image: nginx
  